### ISSUE TITLE
Update version to 8

### ISSUE THREAD

**Issue by AyazBelim** [ShankyTiwari/ng-navigator-share#4]
Can you please update version of this npm package please ?

**Comment by ShankyTiwari** [comment]
@AyazBelim Sure, I'll do this ASAP.

**Comment by ShankyTiwari** [comment]
Hey, @AyazBelim it's updated to Version 8, the current version is [1.0.1](https://www.npmjs.com/package/ng-navigator-share/v/1.0.1), 

Thanks,

**Comment by AyazBelim** [comment]
Thnks @ShankyTiwari
