### ISSUE TITLE
"This service/api is not supported in your Browser" is everywhere!

### ISSUE THREAD

**Issue by atabentoak** [ShankyTiwari/ng-navigator-share#6]
I get this error on Chrome, Android's Chrome, Safari and...
{shared: false, error: "This service/api is not supported in your Browser"}

**Comment by ShankyTiwari** [comment]
You are working on Desktop Browser?

**Comment by atabentoak** [comment]
It's SOLVED.
thanks
I was checking it on localhost, and the problem was with HTTPS
