### ISSUE TITLE
sharing files

### ISSUE THREAD

**Issue by anishchenko-anton** [ShankyTiwari/ng-navigator-share#7]
HI 
how i can  call navigator.canShare() ?? 
is supported sharing files??

**Comment by ShankyTiwari** [comment]
Hi @anishchcenko , there is no such `navigator.canShare()` method in this module, though it's a good to have. I'll add this whenever I'll get time.

Thanks

**Comment by ShankyTiwari** [comment]
Fixed in [1.0.3](https://www.npmjs.com/package/ng-navigator-share/v/1.0.3)
